/**
 * The difficulty registry is now the single source of truth (REF-01).
 *
 * These tests exist to make the "adding a tier is configuration, not code"
 * promise enforceable. If someone reintroduces a hardcoded Easy/Medium/Hard
 * list, or adds a tier without the metadata every consumer needs, this fails.
 */
import { describe, it, expect } from "vitest";
import {
    DIFFICULTIES,
    DIFFICULTY_ENUM,
    DIFFICULTY_TIERS,
    DEFAULT_DIFFICULTY,
    SCORE_WEIGHTS,
    COIN_REWARDS,
    RANK_TIERS,
    coinRewardFor,
    scoreWeightFor,
    difficultyClassName,
    getDifficultyTier,
    getRankTier,
    isDifficulty,
} from "@dwcode/shared";
import { computeScore, getTier } from "@/lib/ranks";

describe("registry integrity", () => {
    it("every tier carries the metadata all consumers need", () => {
        for (const tier of DIFFICULTY_TIERS) {
            expect(tier.id, "id").toBeTruthy();
            expect(tier.label, `${tier.id}.label`).toBeTruthy();
            expect(tier.description, `${tier.id}.description`).toBeTruthy();
            expect(tier.scoreWeight, `${tier.id}.scoreWeight`).toBeGreaterThan(0);
            expect(tier.coinReward, `${tier.id}.coinReward`).toBeGreaterThan(0);
            // Tailwind classes must be complete literals — a constructed string
            // is never generated by the JIT. See the registry's rule 2.
            expect(tier.className.text, `${tier.id}.text`).toMatch(/^text-/);
            expect(tier.className.accent, `${tier.id}.accent`).toMatch(/^before:bg-/);
            expect(tier.className.badge, `${tier.id}.badge`).toContain("text-");
        }
    });

    it("ids are unique", () => {
        expect(new Set(DIFFICULTIES).size).toBe(DIFFICULTIES.length);
    });

    it("order is unique and ascending", () => {
        const orders = DIFFICULTY_TIERS.map((t) => t.order);
        expect(new Set(orders).size).toBe(orders.length);
        expect([...orders]).toEqual([...orders].sort((a, b) => a - b));
    });

    it("harder tiers are worth strictly more", () => {
        // Otherwise the leaderboard rewards grinding volume over skill.
        const byOrder = [...DIFFICULTY_TIERS].sort((a, b) => a.order - b.order);
        for (let i = 1; i < byOrder.length; i++) {
            expect(byOrder[i].scoreWeight).toBeGreaterThan(byOrder[i - 1].scoreWeight);
            expect(byOrder[i].coinReward).toBeGreaterThan(byOrder[i - 1].coinReward);
        }
    });

    it("DIFFICULTY_ENUM is a mutable copy for Mongoose", () => {
        expect(DIFFICULTY_ENUM).toEqual([...DIFFICULTIES]);
        expect(Array.isArray(DIFFICULTY_ENUM)).toBe(true);
    });

    it("the default difficulty is a real tier", () => {
        expect(isDifficulty(DEFAULT_DIFFICULTY)).toBe(true);
    });

    it("derived lookup maps agree with the registry", () => {
        for (const tier of DIFFICULTY_TIERS) {
            expect(SCORE_WEIGHTS[tier.id]).toBe(tier.scoreWeight);
            expect(COIN_REWARDS[tier.id]).toBe(tier.coinReward);
            expect(scoreWeightFor(tier.id)).toBe(tier.scoreWeight);
            expect(coinRewardFor(tier.id)).toBe(tier.coinReward);
            expect(getDifficultyTier(tier.id)).toEqual(tier);
        }
    });
});

describe("unknown difficulties fail safe", () => {
    it("are rejected by the type guard", () => {
        for (const bad of ["", "easy", "Impossible", null, 5, undefined, {}]) {
            expect(isDifficulty(bad)).toBe(false);
        }
    });

    it("score and coins fall back to the MINIMUM, never the maximum", () => {
        // A corrupt or future-tier value must not become the most lucrative
        // thing on the platform.
        const minScore = Math.min(...DIFFICULTY_TIERS.map((t) => t.scoreWeight));
        const minCoins = Math.min(...DIFFICULTY_TIERS.map((t) => t.coinReward));
        expect(scoreWeightFor("Nonexistent")).toBe(minScore);
        expect(coinRewardFor("Nonexistent")).toBe(minCoins);
    });

    it("styling falls back to neutral rather than throwing", () => {
        const cls = difficultyClassName("Nonexistent");
        expect(cls.text).toBeTruthy();
        expect(cls.accent).toBeTruthy();
        expect(cls.badge).toBeTruthy();
    });
});

describe("scoring is tier-count agnostic", () => {
    it("computeScore sums every registry tier", () => {
        const counts = Object.fromEntries(DIFFICULTY_TIERS.map((t) => [t.id, 2]));
        const expected = DIFFICULTY_TIERS.reduce((sum, t) => sum + t.scoreWeight * 2, 0);
        expect(computeScore(counts)).toBe(expected);
    });

    it("computeScore ignores unknown keys instead of mis-scoring them", () => {
        expect(computeScore({ Nonexistent: 100 })).toBe(0);
    });

    it("computeScore treats a missing tier as zero", () => {
        expect(computeScore({})).toBe(0);
    });
});

describe("rank ladder", () => {
    it("is ordered highest-first so first-match works", () => {
        const mins = RANK_TIERS.map((t) => t.min);
        expect([...mins]).toEqual([...mins].sort((a, b) => b - a));
    });

    it("has a zero floor, so every score maps to a tier", () => {
        expect(RANK_TIERS[RANK_TIERS.length - 1].min).toBe(0);
        for (const score of [0, 1, 7, 24, 99, 100, 10_000]) {
            expect(getRankTier(score)).toBeTruthy();
        }
    });

    it("handles negative and non-finite scores without throwing", () => {
        for (const score of [-5, NaN, Infinity, -Infinity]) {
            expect(() => getRankTier(score)).not.toThrow();
            expect(getRankTier(score)).toBeTruthy();
        }
    });

    it("the client's getTier adds presentation for every shared tier", () => {
        for (const tier of RANK_TIERS) {
            const enriched = getTier(tier.min);
            expect(enriched.id).toBe(tier.id);
            expect(enriched.color, `${tier.id}.color`).toBeTruthy();
            expect(enriched.bg, `${tier.id}.bg`).toBeTruthy();
            expect(enriched.icon, `${tier.id}.icon`).toBeTruthy();
        }
    });
});
