/**
 * Stable machine-readable error codes. These are part of the public API contract:
 * the frontend branches on them, so treat renames as breaking changes.
 */
export const ErrorCode = {
  // 400
  VALIDATION_FAILED: "VALIDATION_FAILED",
  BAD_REQUEST: "BAD_REQUEST",
  CLIENT_IDENTITY_REJECTED: "CLIENT_IDENTITY_REJECTED",
  // 401 / 403
  UNAUTHENTICATED: "UNAUTHENTICATED",
  INVALID_TOKEN: "INVALID_TOKEN",
  FORBIDDEN: "FORBIDDEN",
  NOT_OWNER: "NOT_OWNER",
  ADMIN_REQUIRED: "ADMIN_REQUIRED",
  SUPER_ADMIN_REQUIRED: "SUPER_ADMIN_REQUIRED",
  // 404 / 409
  NOT_FOUND: "NOT_FOUND",
  CONFLICT: "CONFLICT",
  ALREADY_EXISTS: "ALREADY_EXISTS",
  DUPLICATE_REQUEST: "DUPLICATE_REQUEST",
  // 413 / 422 / 429
  PAYLOAD_TOO_LARGE: "PAYLOAD_TOO_LARGE",
  UNPROCESSABLE: "UNPROCESSABLE",
  RATE_LIMITED: "RATE_LIMITED",
  ABUSE_DETECTED: "ABUSE_DETECTED",
  // 5xx
  INTERNAL: "INTERNAL",
  NOT_CONFIGURED: "NOT_CONFIGURED",
  UPSTREAM_FAILED: "UPSTREAM_FAILED",
  UPSTREAM_TIMEOUT: "UPSTREAM_TIMEOUT",
} as const;

export type ErrorCodeValue = (typeof ErrorCode)[keyof typeof ErrorCode];
